version: 2
registries:
  github:
    type: npm-registry    #commitsd
    url: https://npm.pkg.github.com
    token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: /javascript
    schedule:
      interval: daily
    allow:
      - dependency-name: "@orolabs/oro-ui-toolkit"
    registries:
      - github
