version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/javascript"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@orolabs/oro-ui-toolkit"
    registries:
      - github
registries:
  github:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{ secrets.DEPENDABOT_GITHUB_TOKEN }}"
